import { colorPrimitives } from '../primitives/colors'

export const semanticColors = {
  "Admin Action": {
    "Admin Action Background": "#1447e6",
    "Admin Action Background Hover": "#1c398e",
    "Admin Action Background Pressed": "#132767",
    "Admin Action Background Weak Hover": "#eff6ff",
    "Admin Action Background Weak Pressed": "#dbeafe",
    "Admin Action Text": "#1447e6",
    "Admin Action Text Hover": "#193cb8",
    "Admin Action Text Pressed": "#132767",
    "Admin Action Icon": "#1447e6",
    "Admin Action Icon Hover": "#193cb8",
    "Admin Action Icon Pressed": "#132767",
    "Admin Action Text Inverse": "#ffffff",
    "Admin Action Icon Inverse": "#ffffff",
    "Admin Action Border Inverse": "#ffffff",
    "Admin Action Border": "#1447e6",
    "Admin Action Border Hover": "#193cb8",
    "Admin Action Border Pressed": "#1c398e",
    "Admin Action Border Weak": "#51a2ff",
    "🚀 Admin Action Container Hover": "#1447e61a"
  },
  "Consumer Action": {
    "Consumer Action Background": "#fa6700",
    "Consumer Action Background Hover": "#f54900",
    "Consumer Action Background Pressed": "#ca3500",
    "Consumer Action Border": "#fa6700",
    "Consumer Action Border Hover": "#f54900",
    "Consumer Action Border Pressed": "#ca3500",
    "Consumer Action Border Weak": "#f8944c",
    "Consumer Action Text": "#fa6700",
    "Consumer Action Text Hover": "#f54900",
    "Consumer Action Text Pressed": "#ca3500",
    "Consumer Action Background Weak Hover": "#fff7ed",
    "Consumer Action Background Weak Pressed": "#ffedd4",
    "Consumer Action Icon": "#fa6700",
    "Consumer Action Icon Hover": "#f54900",
    "Consumer Action Icon Pressed": "#ca3500"
  },
  "Neutral": {
    "Neutral Background": "#ffffff",
    "Neutral Background Disabled": "#e5e7eb",
    "Neutral Background Weak": "#f9fafb",
    "Neutral Background Weak Disabled": "#f3f4f6",
    "Neutral Background Medium": "#f3f4f6",
    "Neutral Background Strong": "#e5e7eb",
    "Neutral Background Strongest": "#6a7282",
    "Neutral Background Inverse": "#1e2939",
    "Neutral Text": "#101828",
    "Neutral Text Medium": "#4a5565",
    "[audit] Neutral Text Weak": "#99a1af",
    "Neutral Text Disabled": "#99a1af",
    "Neutral Icon": "#101828",
    "Neutral Icon Medium": "#4a5565",
    "Neutral Icon Weak": "#99a1af",
    "Neutral Icon Disabled": "#99a1af",
    "Neutral Border": "#d1d5dc",
    "Neutral Border Disabled": "#99a1af",
    "Neutral Border Medium": "#99a1af",
    "Neutral Text Inverse": "#ffffff",
    "Neutral Icon Inverse": "#ffffff"
  },
  "Negative": {
    "Negative Background": "#e60707",
    "Negative Background Hover": "#cf0f0f",
    "Negative Background Pressed": "#b40101",
    "Negative Background Weak": "#fdd7d3",
    "Negative Background Weak Hover": "#ffeeed",
    "Negative Background Weak Pressed": "#fdd7d3",
    "Negative Text": "#e60707",
    "Negative Text Hover": "#cf0f0f",
    "Negative Text Pressed": "#b40101",
    "Negative Icon": "#e60707",
    "Negative Icon Hover": "#cf0f0f",
    "Negative Icon Pressed": "#b40101",
    "Negative Border": "#e60707",
    "Negative Border Hover": "#cf0f0f",
    "Negative Border Pressed": "#b40101"
  },
  "Positive": {
    "Positive Background": "#5c9f03",
    "Positive Background Hover": "#3c6300",
    "Positive Background Pressed": "#264400",
    "Positive Background Medium": "#bbf451",
    "Positive Background Weak": "#ecfcca",
    "Positive Background Weak Hover": "#f7fee7",
    "Positive Background Weak Pressed": "#d8f999",
    "Positive Text": "#3c6300",
    "Positive Text Hover": "#264400",
    "Positive Text Pressed": "#22330c",
    "Positive Icon": "#3c6300",
    "Positive Icon Hover": "#264400",
    "Positive Icon Pressed": "#22330c",
    "Positive Border": "#3c6300",
    "Positive Border Hover": "#264400",
    "Positive Border Pressed": "#22330c"
  },
  "Info": {
    "Info Background": "#51a2ff",
    "Info Background Medium": "#8ec5ff",
    "Info Background Weak": "#dbeafe",
    "Info Border": "#1447e6",
    "Info Text": "#1447e6",
    "Info Icon": "#1447e6"
  },
  "Caution": {
    "Caution Background": "#ffec44",
    "Caution Background Weak": "#fff9c2",
    "Caution Border": "#fff498",
    "Caution Icon": "#9e8f0b",
    "Caution Text": "#9e8f0b"
  },
  "Accent": {
    "Accent Background": "#fa6700",
    "Accent Background Medium": "#ffd6a8",
    "Accent Background Weak": "#fff7ed",
    "Accent Text Medium": "#9f2d00",
    "Accent Border Weak": "#ffb86a"
  },
  "Live": {
    "Live Background": "#ff3838",
    "Live Text": "#ffffff"
  },
  "Brand": {
    "Brand Background": "#1c398e",
    "Brand Background Strong": "#001f4d"
  },
  "Component Color Tokens": {
    "Secondary Button Background": "#ffffff"
  },
  "Deprecated": {
    "[deprecated] Action Background Weak": "#eff6ff",
    "[deprecated] Action Text Weak": "#1c398e",
    "[deprecated] Action Border Focused-Active": "#193cb8",
    "[deprecated] Caution Text": "#ca3500",
    "[deprecated] Caution Icon Medium": "#f54900",
    "[deprecated] Negative Background Weak": "#ffeeed",
    "[deprecated] Negative Background Disabled": "#ffbab4",
    "[deprecated] Negative Text Disabled": "#ff9187",
    "[deprecated] Negative Icon Disabled": "#ff9187",
    "[deprecated] Negative Border Disabled": "#ff9187",
    "[deprecated] Positive Background Weak": "#f7fee7",
    "[deprecated] Positive Background Disabled": "#bbf451",
    "[deprecated] Positive Text Disabled": "#bbf451",
    "[deprecated] Positive Icon Disabled": "#bbf451",
    "[deprecated] Positive Border Disabled": "#bbf451"
  }
} as const

// Dark mode colors (Dark(WIP) mode from Figma)
export const semanticColorsDark = {
  "Admin Action": {
    "Admin Action Background": "#1447e6",
    "Admin Action Background Hover": "#155dfc",
    "Admin Action Background Pressed": "#2b7fff",
    "Admin Action Background Weak Hover": "#1c398e",
    "Admin Action Background Weak Pressed": "#193cb8",
    "Admin Action Text": "#8ec5ff",
    "Admin Action Text Hover": "#bedbff",
    "Admin Action Text Pressed": "#dbeafe",
    "Admin Action Icon": "#8ec5ff",
    "Admin Action Icon Hover": "#bedbff",
    "Admin Action Icon Pressed": "#dbeafe",
    "Admin Action Text Inverse": "#050c1a",
    "Admin Action Icon Inverse": "#050c1a",
    "Admin Action Border Inverse": "#050c1a",
    "Admin Action Border": "#8ec5ff",
    "Admin Action Border Hover": "#bedbff",
    "Admin Action Border Pressed": "#dbeafe",
    "Admin Action Border Weak": "#8ec5ff",
    "🚀 Admin Action Container Hover": "#1447e61a"
  },
  "Consumer Action": {
    "Consumer Action Background": "#fa6700",
    "Consumer Action Background Hover": "#ff8025",
    "Consumer Action Background Pressed": "#f8944c",
    "Consumer Action Border": "#fa6700",
    "Consumer Action Border Hover": "#ff8025",
    "Consumer Action Border Pressed": "#f8944c",
    "Consumer Action Border Weak": "#f8944c",
    "Consumer Action Text": "#fa6700",
    "Consumer Action Text Hover": "#ff8025",
    "Consumer Action Text Pressed": "#f8944c",
    "Consumer Action Background Weak Hover": "#9f2d00",
    "Consumer Action Background Weak Pressed": "#ca3500",
    "Consumer Action Icon": "#fa6700",
    "Consumer Action Icon Hover": "#ff8025",
    "Consumer Action Icon Pressed": "#f8944c"
  },
  "Neutral": {
    "Neutral Background": "#000000",
    "Neutral Background Disabled": "#4a5565",
    "Neutral Background Weak": "#101828",
    "Neutral Background Weak Disabled": "#4a5565",
    "Neutral Background Medium": "#1e2939",
    "Neutral Background Strong": "#6a7282",
    "Neutral Background Strongest": "#6a7282",
    "Neutral Background Inverse": "#f9fafb",
    "Neutral Text": "#ffffff",
    "Neutral Text Medium": "#f3f4f6",
    "[audit] Neutral Text Weak": "#e5e7eb",
    "Neutral Text Disabled": "#99a1af",
    "Neutral Icon": "#ffffff",
    "Neutral Icon Medium": "#f3f4f6",
    "Neutral Icon Weak": "#f3f4f6",
    "Neutral Icon Disabled": "#99a1af",
    "Neutral Border": "#6a7282",
    "Neutral Border Disabled": "#99a1af",
    "Neutral Border Medium": "#99a1af",
    "Neutral Text Inverse": "#000000",
    "Neutral Icon Inverse": "#000000"
  },
  "Negative": {
    "Negative Background": "#e60707",
    "Negative Background Hover": "#ffbab4",
    "Negative Background Pressed": "#fdd7d3",
    "Negative Background Weak": "#cf0f0f",
    "Negative Background Weak Hover": "#b40101",
    "Negative Background Weak Pressed": "#cf0f0f",
    "Negative Text": "#ff9187",
    "Negative Text Hover": "#ffbab4",
    "Negative Text Pressed": "#fdd7d3",
    "Negative Icon": "#ff9187",
    "Negative Icon Hover": "#cf0f0f",
    "Negative Icon Pressed": "#b40101",
    "Negative Border": "#ff0404",
    "Negative Border Hover": "#cf0f0f",
    "Negative Border Pressed": "#b40101"
  },
  "Positive": {
    "Positive Background": "#5c9f03",
    "Positive Background Hover": "#3c6300",
    "Positive Background Pressed": "#264400",
    "Positive Background Medium": "#bbf451",
    "Positive Background Weak": "#3c6300",
    "Positive Background Weak Hover": "#477502",
    "Positive Background Weak Pressed": "#5c9f03",
    "Positive Text": "#ecfcca",
    "Positive Text Hover": "#3c6300",
    "Positive Text Pressed": "#264400",
    "Positive Icon": "#ecfcca",
    "Positive Icon Hover": "#3c6300",
    "Positive Icon Pressed": "#264400",
    "Positive Border": "#ecfcca",
    "Positive Border Hover": "#3c6300",
    "Positive Border Pressed": "#264400"
  },
  "Info": {
    "Info Background": "#51a2ff",
    "Info Background Medium": "#8ec5ff",
    "Info Background Weak": "#8ec5ff",
    "Info Border": "#1447e6",
    "Info Text": "#1447e6",
    "Info Icon": "#1447e6"
  },
  "Caution": {
    "Caution Background": "#ffec44",
    "Caution Background Weak": "#fff9c2",
    "Caution Border": "#fff498",
    "Caution Icon": "#efdd41",
    "Caution Text": "#efdd41"
  },
  "Accent": {
    "Accent Background": "#fa6700",
    "Accent Background Medium": "#ffd6a8",
    "Accent Background Weak": "#fff7ed",
    "Accent Text Medium": "#ca3500",
    "Accent Border Weak": "#ffb86a"
  },
  "Live": {
    "Live Background": "#ff3838",
    "Live Text": "#ffffff"
  },
  "Brand": {
    "Brand Background": "#1c398e",
    "Brand Background Strong": "#001f4d"
  },
  "Component Color Tokens": {
    "Secondary Button Background": "#000000"
  },
  "Deprecated": {
    "[deprecated] Action Background Weak": "#eff6ff",
    "[deprecated] Action Text Weak": "#1c398e",
    "[deprecated] Action Border Focused-Active": "#193cb8",
    "[deprecated] Caution Text": "#ca3500",
    "[deprecated] Caution Icon Medium": "#f54900",
    "[deprecated] Negative Background Weak": "#ffeeed",
    "[deprecated] Negative Background Disabled": "#ffbab4",
    "[deprecated] Negative Text Disabled": "#ff9187",
    "[deprecated] Negative Icon Disabled": "#ff9187",
    "[deprecated] Negative Border Disabled": "#ff9187",
    "[deprecated] Positive Background Weak": "#f7fee7",
    "[deprecated] Positive Background Disabled": "#bbf451",
    "[deprecated] Positive Text Disabled": "#bbf451",
    "[deprecated] Positive Icon Disabled": "#bbf451",
    "[deprecated] Positive Border Disabled": "#bbf451"
  }
} as const
